[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
# DEFMT_LOG = "warn" # touch Cargo.toml to rebuild


[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip=RP2040"

# [target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "elf2uf2-rs -ds target/thumbv6m-none-eabi/debug/dua_blinka"

rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tlink-rp.x",
    "-C",
    "link-arg=-Tdefmt.x",
]
